### PR TITLE
Rewards: solved infinite monthly average bug

### LINKED ISSUE #1414: Math issue for Monthly average in overview tab
Resulting in "infinity"

https://www.dropbox.com/s/c8q18nmetzqfg5a/Screen%20Shot%202019-10-23%20at%2011.19.36%20AM.png?dl=0

### PR DESCRIPTION
**Pull request by e18r**
Fixes #1414 

Before: 
sR1NY0tw

After:
Screenshot from 2019-10-23 09-19-12

### CODE REVIEW

File: apps/rewards/app/utils/metric-utils.js [hunk 1]
```diff
@@ -28,16 +28,22 @@ const calculateMonthlyAvg = (rewards, balances, convertRates) => {
...
   }
-  let monthCount = Math.ceil((rewards.reduce((minDate, reward) => {
-    return reward.endDate < minDate.endDate ? reward: minDate
-  }, rewards[0]).endDate - Date.now())/ MILLISECONDS_IN_A_MONTH)
+  const earliestReward = rewards.reduce(
+    (minDate, reward) => {
+      return reward.endDate < minDate.endDate ? reward : minDate
+    },
+    rewards[0]
+  )
```
Comment (chadoh) [inline apps/rewards/app/utils/metric-utils.js]: I find this pretty confusing. Maybe we could do something like this instead:
```suggestion
  const earliestEndDate = Math.min(...rewards.map(r => r.endDate))
```

**Comment by e18r** [comment]
hey @chadoh, thanks for merging, sorry I couldn't make the change before
