### PR TITLE
Allocation: add support for tokens with different decimal amounts

### LINKED ISSUE #1646: Allocation/New budget: upon creation, budget is set to zero for an unknown reason
**Describe the bug**
I tried to set a budget using an ECR20 token (EF2), whose contract address is:
0xb23d5c1d53c70e59eb863e409923577eb42f809b
Once created, the budget has a value of zero, even though a non-zero value was submitted.

**Mainnet or testnet?**
Rinkeby

**Organization**
oetest3, efdaotest03

**To Reproduce**
Assuming you have some EF2 tokens (I can send some to you):
1. Deposit EF2 via the Finance app
2. Go to Allocation
3. Click on New budget
4. Select EF2 and type a number of tokens
5. Create the transaction
6. See the result: the budget is 0 EF2 (see screenshots)

**Expected behavior**
The budget should show the value submitted by the user

**Screenshots**
image

image

**Desktop (please complete the following information):**
 - OSX 10.13
 - Chrome + Metamask

### PR DESCRIPTION
**Pull request by e18r**
Fixes #1646

The `displayAmount` helper function assumed that every token amount had 18 decimals, which caused trouble with any token with a different amount of decimals. I corrected that helper function and put it in
`shared/ui` so that other apps can benefit from it in the future.

### CODE REVIEW

File: apps/allocations/app/components/App/AllocationsHistory.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ const AllocationsHistory = ({ allocations, skipBudgetColumn }) => {
           description,
           <Status key={index} code={status} />,
           <Amount key={index} theme={theme} >
-            { displayCurrency(BigNumber(-amount)) } { getTokenSymbol(token) }
+            { displayCurrency(-amount) } { getTokenSymbol(token) }
```
Comment (Quazia) [inline apps/allocations/app/components/App/AllocationsHistory.js]: Shouldn't we be using `decimalsNumber` here as well?

File: apps/allocations/app/components/App/Payouts.js [hunk 2]
```diff
@@ -99,7 +99,7 @@ const PayoutsNarrow = ({ executePayout, data, tokens }) => (
         <div css="display: flex; flex-wrap: nowrap; align-items: center">
           <div css="margin-right: 10px">
             <AmountBadge>
-              {displayCurrency(BigNumber(payout.amount))}{' '}{translateToken(payout.token, tokens)}
+              {displayCurrency(payout.amount)}{' '}{translateToken(payout.token, tokens)}
```
Comment (Quazia) [inline apps/allocations/app/components/App/Payouts.js]: Same here?

**Comment by e18r** [comment]
I'm not sure what happened here. @rkzel did you merge this and then reverted the merge? Does this still need to be reviewed and merged?
