### PR TITLE
Allocations: set a fixed width for recipients container

### LINKED ISSUE #1419: Allocations history -- the bar width should be decoupled from the identity badge width
Screenshot of the problem:
image

### PR DESCRIPTION
**Pull request by e18r**
Fixes #1419 

Screenshot from 2019-10-25 13-38-28

### CODE REVIEW

File: apps/allocations/app/components/App/AllocationsHistory.js [hunk 1]
```diff
@@ -74,7 +74,7 @@ const AllocationsHistory = ({ allocations }) => {
         return recipients.map((recipient, index) => {
           const allocated = BigNumber(recipient.supports).div(totalSupports)
           return (
-            <div key={index}>
+            <RecipientContainer key={index}>
```
Comment (chadoh) [inline apps/allocations/app/components/App/AllocationsHistory.js]: While we're here, I'd love to get rid of the unnecessary `index` variable and use `key={recipient.candidateAddress}` instead.

File: apps/allocations/app/components/App/AllocationsHistory.js [hunk 2]
```diff
@@ -123,6 +123,10 @@ const Amount = styled.div`
   font-weight: 600;
 `
 
+const RecipientContainer = styled.div`
+  width: 50%;
```
Comment (chadoh) [inline apps/allocations/app/components/App/AllocationsHistory.js]: How does this look on mobile?

Comment (topocount) [reply apps/allocations/app/components/App/AllocationsHistory.js]: @chadoh this looks okay for me. The location of the detail expansion in this block bothers me a bit, but that's not enought to prevent a merge in my opinion

image
